AWSTemplateFormatVersion: "2010-09-09"
Description: A single-AZ database.

Resources:
  Database:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: db.t3.medium
      Engine: postgres
      AllocatedStorage: 100
      StorageType: gp3
      MultiAZ: false
      BackupRetentionPeriod: 7
      Tags:
        - Key: Environment
          Value: development
        - Key: Application
          Value: payments
