AWSTemplateFormatVersion: "2010-09-09"
Description: An application server.

Resources:
  ApplicationServer:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.small
      Tags:
        - Key: Environment
          Value: development
        - Key: Application
          Value: payments
